### ISSUE TITLE
Turn these into gallery items

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#503]
Turn these into gallery items, or just dump them (decide for each node)

We shouldn't lose production experience gained through / stored inside any of these nodes, so if something has worth it, it should be kept!

@gadfly16 weigh in :)

(future)

~~Attr Lookup Multi qL SOP~~
- looks very much like Attrib Ramp qL SOP, but it uses CHOPs (not multithreaded) and deals with geometry
- dump

~~Match Points Order qL SOP~~
- gallery item?

~~PolyWireCurves qL SOP~~
- Houdini has Convert Line SOP
- dump

~~PrimGroup Add IDs SOP~~
- i think this is redundant now, dump

~~Scatter qL SOP~~
- turn this into a gallery item using the latest Scatter SOP

~~Split Multi qL SOP~~
- gallery item

~~Round Corners qL SOP~~
- see #64 
- ???

~~Rounded Rectangle qL SOP - gallery item~~

(experimental)

~~Alembic Reapply Xform qL SOP~~
- gallery item or just dump

~~Connect by Distance qL SOP~~
- gallery item #389

~~Illustration qL SOP~~
- gallery item or dump

~~Null qL OBJ~~
- DUMP its ass

~~Reference qL SOP~~
- unfinished. see help for intentions. dump?

~~VDB Export qL SOP~~
- (jq) I'd be _so_ glad to dump this thing for some reason

(base)

~~Arc Blend qL SOP~~
- gallery item, dump, or useful? @gadfly16 

~~Cardinal qL SOP~~
- H15+ resample could do more or less the same thing but it still crashes
- dump? NOT YET

~~Hexa Grid qL SOP - gallery item~~

~~Point Texture qL SOP~~
- #70 #74 #82 #145 

~~Sweep qL SOP~~
- #359 

~~Thickness qL SOP~~
- what's the advantage over a Ray SOP?
- should be cleaned up _or_ dumped

~~Triangle Grid qL SOP - gallery item~~

**Comment by gadfly16** [comment]
Huhh, it's a lot. You're boss, but I'm happy to discuss. I need some time though to dive deep enough to give educated answers. It all happened so loooong ago. For now what I'm sure about is the following:

0. Match Point Order was useful for character modelling and set-up. I really don't know if it still is or not? Is it made by you or me?
0. PolyWireCurves can be ditched.
0. Inclusion of Rounded Rectangle is really a matter of taste. It's useful when needed, but I don't know how often is that. Since I don't really use GIs (my bad) I can not judge this. How fast is to access GIs, what is your default way to get to them?
0. Connect By Distance is also useful in my opinion, but I have some memories that I bumped into some native tool that could do its job more efficiently. Any idea?
0. Arc Blend is useful when you're setting up blend shape animation for an eyelid. A tutorial video would be more desirable than ditching. That's a simple but nice one, that I'm kind of proud of.
0. Point Texture can be ditched.
0. I need to look at Thickness and Sweep to answer.
0 Triangle and Hexa grid are in the same category as Rounded Rectangle in my op.

I have no opinion on the others. Their fate is up to you, I guess.
